#!/usr/bin/env bash

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Configurations --------------------------------------------#
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV'
		bspc monitor ${monitor} -n "$name" -d '東' '西' '南' '北'
		#bspc monitor ${monitor} -n "$name" -d '' '' '' '' 
		let name++
	done
}
workspaces

bspc config border_width 2
bspc config window_gap 18
bspc config split_ratio 0.53

#bspc config focused_border_color \#F9F9FB
#bspc config normal_border_color \#D2D8E0

bspc config focused_border_color \#F8C3B5
bspc config normal_border_color #282828
bspc config active_border_color \#F8C3B5
bspc config presel_feedback_color #F8C3B5

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

# 1 > terminal
bspc rule -a Tilix  desktop='^1' follow=on focus=on
bspc rule -a kitty desktop='^1' follow=on focus=on

# 2 > web
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a Chromium desktop='^2' follow=on focus=on

# 3 > files
declare -a files=(Pcmanfm Thunar qBittorrent)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

# 4 > code
declare -a code=(Geany code-oss)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

# special rules
declare -a floating=(alacritty-float Pcmanfm Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager

# Lauch xsettingsd daemon
xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# ****
exec mpd &
nitrogen --restore &
picom &
polybar &
